"""Notification — format and create GitHub Issues for new positions."""

from __future__ import annotations

import os
from datetime import datetime, timezone

import requests

from config import REQUEST_TIMEOUT
from models import Job


def format_issue_body(all_new_jobs: list[tuple[dict, list[Job]]]) -> str:
    """Format the GitHub Issue body as Markdown."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    total_new = sum(len(jobs) for _, jobs in all_new_jobs)
    total_companies = len(all_new_jobs)

    lines = [
        "# New Positions Found\n",
        f"**Date:** {now}  ",
        f"**Companies with new positions:** {total_companies}  ",
        f"**Total new positions:** {total_new}\n",
        "---\n",
    ]

    for company, jobs in all_new_jobs:
        ats_label = company["ats"].capitalize()
        lines.append(f"## {company['name']} ({ats_label})\n")

        has_department = any(job.get("department") for job in jobs)
        if has_department:
            lines.append("| Title | Department | Location | Posted | Link |")
            lines.append("|-------|------------|----------|--------|------|")
        else:
            lines.append("| Title | Location | Posted | Link |")
            lines.append("|-------|----------|--------|------|")

        for job in jobs:
            title = job["title"]
            location = job.get("location", "N/A") or "N/A"
            posted = job.get("posted_date", "N/A") or "N/A"
            if posted and posted != "N/A":
                posted = posted[:10]
            url = job.get("url", "")
            link = f"[Apply]({url})" if url else "N/A"

            if has_department:
                dept = job.get("department", "N/A") or "N/A"
                lines.append(f"| {title} | {dept} | {location} | {posted} | {link} |")
            else:
                lines.append(f"| {title} | {location} | {posted} | {link} |")

        lines.append("")

    lines.append("---")
    lines.append(
        "*Generated by [NewPositionMonitor]"
        "(https://github.com/liuyixiaohu/new-position-monitor)*"
    )

    return "\n".join(lines)


def _build_issue_title(filters: dict | None) -> str:
    """Build a descriptive issue title from the active filter config."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    if not filters:
        return f"New Positions - {now}"

    # Derive a human-readable label from role_keywords
    role_keywords = filters.get("role_keywords", [])
    intern_keywords = filters.get("intern_keywords", [])

    parts = []
    if intern_keywords:
        parts.append("Intern")
    if role_keywords:
        # Use the first role keyword as the descriptor
        parts.append(role_keywords[0].title())

    label = " ".join(parts) if parts else "Job"
    return f"New {label} Positions - {now}"


def notify(
    all_new_jobs: list[tuple[dict, list[Job]]],
    filters: dict | None = None,
) -> None:
    """Send notification about new positions.

    In CI (GITHUB_TOKEN set), creates a GitHub Issue.
    Locally, prints to stdout.
    """
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    body = format_issue_body(all_new_jobs)

    if not token or not repo:
        print("\n--- GitHub Issue Preview (GITHUB_TOKEN not set) ---")
        print(body)
        print("--- End Preview ---\n")
        return

    title = _build_issue_title(filters)

    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {
        "title": title,
        "body": body,
        "labels": ["new-positions"],
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        issue_url = resp.json().get("html_url", "")
        print(f"GitHub Issue created: {issue_url}")
    except requests.RequestException as e:
        print(f"Failed to create GitHub Issue: {e}")
        print("Falling back to stdout:")
        print(body)
